In [104]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from bokeh.plotting import figure
from bokeh.io import output_file, show, save
import pandas
from bokeh.models import DataRange1d, PanTool, ResetTool, WheelZoomTool, HoverTool, LassoSelectTool, BoxSelectTool, SaveTool, Legend

In [105]:
def normalize(input_data, column):
    values = []
    
    for value in input_data[column]:
         values.append(value)
            
    Min = min(values)
    Max = max(values)
        
    output_data = []
    for value in input_data[column]:
        output_data.append((value - Min)/(Max - Min))
    
    input_data['Normalized_data'] = output_data
    
    return input_data

In [106]:
def select_plot(input_data,origin, year1, year2):
    input_data = input_data.loc[input_data['Origin'] == origin]
    input_data = input_data.loc[(input_data['Timestamp'] > year1) & (input_data['Timestamp'] < year2)]
    return input_data

In [107]:
# change dir to access preprocessed data

import os
print(os.getcwd())
os.chdir("../../../")
os.chdir("klad/Midas/Middle-East")
print(os.getcwd())

raw_data = pd.read_csv('refugees_middle_east_per_timestamp.csv')
df1 = pd.DataFrame(raw_data)

C:\Users\Midas\Documents\GitHub\DataProcessing1\datasets\preprocessed datasets\Food prices
C:\Users\Midas\Documents\GitHub\DataProcessing1\klad\Midas\Middle-East

In [108]:
def select_plot_foodprices_per_market(input_data, country, product, year1, year2):
    input_data = input_data.loc[input_data['adm0_name'] == country]
    input_data = input_data.loc[input_data['cm_name'] == product]
    input_data = input_data.loc[(input_data['Year'] >= year1) & (input_data['Year'] < year2 + 1)]
    return input_data

In [109]:
def select_plot_foodprices_average(input_data, country, product, year1, year2):
    input_data = select_plot_foodprices_per_market(input_data, country, product, year1, year2)
    
    country_list = []
    product_list = []
    average_price_list = []
    year_list = []
    
    for i in range(year1, year2 + 1):
        for j in range(12):
#             Selecteer een specifieke maand in een jaar
            output_data = input_data.loc[input_data['mp_year'] == i]
            output_data = output_data.loc[output_data['mp_month'] == j + 1]
#         maak een nieuwe rij wanneer er data beschikbaar is
            if len(output_data['mp_price']) > 0:
#                 year
                year_list.append(i + (j / 12))

#                 country
                country_list.append(country)

#                 product
                product_list.append(product)
#                 average data            
                average_price_list.append(sum(output_data['mp_price']) / len(output_data['mp_price']))
            else:
                print('ERROR: Geen data beschikbaar over het jaar', i + j/12)
    
    output_data = pd.DataFrame()    
    output_data['country'] = country_list
    output_data['year'] = year_list
    output_data['product'] = product_list
    output_data['average_price'] = average_price_list
    return output_data

In [110]:
import os
print(os.getcwd())
os.chdir("../../../")
os.chdir("datasets/preprocessed datasets/Food prices")
print(os.getcwd())

raw_data = pd.read_csv('Food_prizes_MiddleEast_processed.csv')
df2 = pd.DataFrame(raw_data)

normalize(df2, 'mp_price')

C:\Users\Midas\Documents\GitHub\DataProcessing1\klad\Midas\Middle-East
C:\Users\Midas\Documents\GitHub\DataProcessing1\datasets\preprocessed datasets\Food prices

,Unnamed: 0,adm0_name,adm1_name,mkt_name,cm_name,cur_name,pt_name,um_id,um_name,mp_month,mp_year,mp_price,Year,Normalized_data
0,636073,Syrian Arab Republic,City-Damascus,Sheikh Sa'ad,Rice,SYP,Retail,5,KG,7,2012,55.0000,2012.500000,0.000009
1,636074,Syrian Arab Republic,City-Damascus,Sheikh Sa'ad,Rice,SYP,Retail,5,KG,8,2012,80.0000,2012.583333,0.000014
2,636075,Syrian Arab Republic,City-Damascus,Sheikh Sa'ad,Rice,SYP,Retail,5,KG,9,2012,80.0000,2012.666667,0.000014
3,636076,Syrian Arab Republic,City-Damascus,Sheikh Sa'ad,Rice,SYP,Retail,5,KG,5,2013,95.0000,2013.333333,0.000016
4,636077,Syrian Arab Republic,City-Damascus,Sheikh Sa'ad,Rice,SYP,Retail,5,KG,6,2013,106.2500,2013.416667,0.000018
5,636078,Syrian Arab Republic,City-Damascus,Sheikh Sa'ad,Rice,SYP,Retail,5,KG,7,2013,188.0000,2013.500000,0.000032
6,636079,Syrian Arab Republic,City-Damascus,Sheikh Sa'ad,Rice,SYP,Retail,5,KG,8,2013,295.0000,2013.583333,0.000051
7,636080,Syrian Arab Republic,City-Damascus,Sheikh Sa'ad,Rice,SYP,Retail,5,KG,9,2013,275.0000,2013.666667,0.000047
8,636081,Syrian Arab Republic,City-Damascus,Sheikh Sa'ad,Rice,SYP,Retail,5,KG,10,2013,295.0000,2013.750000,0.000051
9,636082,Syrian Arab Republic,City-Damascus,Sheikh Sa'ad,Rice,SYP,Retail,5,KG,11,2013,295.0000,2013.833333,0.000051
10,636083,Syrian Arab Republic,City-Damascus,Sheikh Sa'ad,Rice,SYP,Retail,5,KG,12,2013,295.0000,2013.916667,0.000051
11,636084,Syrian Arab Republic,City-Damascus,Sheikh Sa'ad,Rice,SYP,Retail,5,KG,1,2014,147.0000,2014.000000,0.000025
12,636085,Syrian Arab Republic,City-Damascus,Sheikh Sa'ad,Rice,SYP,Retail,5,KG,2,2014,181.2500,2014.083333,0.000031
13,636086,Syrian Arab Republic,City-Damascus,Sheikh Sa'ad,Rice,SYP,Retail,5,KG,3,2014,196.6667,2014.166667,0.000034
14,636087,Syrian Arab Republic,City-Damascus,Sheikh Sa'ad,Rice,SYP,Retail,5,KG,4,2014,208.3333,2014.250000,0.000036
15,636088,Syrian Arab Republic,City-Damascus,Sheikh Sa'ad,Rice,SYP,Retail,5,KG,5,2014,190.0000,2014.333333,0.000033
16,636089,Syrian Arab Republic,City-Damascus,Sheikh Sa'ad,Rice,SYP,Retail,5,KG,6,2014,193.7500,2014.416667,0.000033
17,636090,Syrian Arab Republic,City-Damascus,Sheikh Sa'ad,Rice,SYP,Retail,5,KG,7,2014,193.7500,2014.500000,0.000033
18,636091,Syrian Arab Republic,City-Damascus,Sheikh Sa'ad,Rice,SYP,Retail,5,KG,8,2014,217.5000,2014.583333,0.000037
19,636092,Syrian Arab Republic,City-Damascus,Sheikh Sa'ad,Rice,SYP,Retail,5,KG,9,2014,217.5000,2014.666667,0.000037
20,636093,Syrian Arab Republic,City-Damascus,Sheikh Sa'ad,Rice,SYP,Retail,5,KG,10,2014,211.2500,2014.750000,0.000036
21,636094,Syrian Arab Republic,City-Damascus,Sheikh Sa'ad,Rice,SYP,Retail,5,KG,11,2014,235.0000,2014.833333,0.000040
22,636095,Syrian Arab Republic,City-Damascus,Sheikh Sa'ad,Rice,SYP,Retail,5,KG,12,2014,218.0000,2014.916667,0.000037
23,636096,Syrian Arab Republic,City-Damascus,Sheikh Sa'ad,Rice,SYP,Retail,5,KG,1,2015,238.0000,2015.000000,0.000041
24,636097,Syrian Arab Republic,City-Damascus,Sheikh Sa'ad,Rice,SYP,Retail,5,KG,2,2015,228.0000,2015.083333,0.000039
25,636098,Syrian Arab Republic,City-Damascus,Sheikh Sa'ad,Rice,SYP,Retail,5,KG,3,2015,258.0000,2015.166667,0.000044
26,636099,Syrian Arab Republic,City-Damascus,Sheikh Sa'ad,Rice,SYP,Retail,5,KG,4,2015,272.5000,2015.250000,0.000047
27,636100,Syrian Arab Republic,City-Damascus,Sheikh Sa'ad,Rice,SYP,Retail,5,KG,5,2015,197.0000,2015.333333,0.000034
28,636101,Syrian Arab Republic,City-Damascus,Sheikh Sa'ad,Rice,SYP,Retail,5,KG,6,2015,215.0000,2015.416667,0.000037
29,636102,Syrian Arab Republic,City-Damascus,Sheikh Sa'ad,Rice,SYP,Retail,5,KG,7,2015,215.0000,2015.500000,0.000037
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60291,237261,Iran (Islamic Republic of),Tehran,Tehran Market,Lentils,IRR,Retail,5,KG,4,2015,65630.0000,2015.250000,0.011251
60292,237262,Iran (Islamic Republic of),Tehran,Tehran Market,Lentils,IRR,Retail,5,KG,5,2015,53050.0000,2015.333333,0.009094
60293,237263,Iran (Islamic Republic of),Tehran,Tehran Market,Lentils,IRR,Retail,5,KG,6,2015,75930.0000,2015.416667,0.013017
60294,237264,Iran (Islamic Republic of),Tehran,Tehran Market,Lentils,IRR,Retail,5,KG,7,2015,77600.0000,2015.500000,0.013303
60295,237265,Iran (Islamic Republic of),Tehran,Tehran Market,Lentils,IRR,Retail,5,KG,8,2015,79690.0000,2015.583333,0.013661
60296,237266,Iran (Islamic Republic of),Tehran,Tehran Market,Lentils,IRR,Retail,5,KG,9,2015,79660.0000,2015.666667,0.013656
60297,237267,Iran (Islamic Republic of),Tehran,Tehran Market,Lentils,IRR,Retail,5,KG,10,2015,80220.0000,2015.750000,0.013752
60298,237268,Iran (Islamic Republic of),Tehran,Tehran Market,Lentils,IRR,Retail,5,KG,11,2015,89370.0000,2015.833333,0.015321
60299,237269,Iran (Islamic Republic of),Tehran,Tehran Market,Lentils,IRR,Retail,5,KG,12,2015,87800.0000,2015.916667,0.015051
60300,237270,Iran (Islamic Republic of),Tehran,Tehran Market,Lentils,IRR,Retail,5,KG,1,2016,89050.0000,2016.000000,0.015266
60301,237271,Iran (Islamic Republic of),Tehran,Tehran Market,Lentils,IRR,Retail,5,KG,2,2016,94610.0000,2016.083333,0.016219
60302,237272,Iran (Islamic Republic of),Tehran,Tehran Market,Lentils,IRR,Retail,5,KG,3,2016,93770.0000,2016.166667,0.016075
60303,237273,Iran (Islamic Republic of),Tehran,Tehran Market,Lentils,IRR,Retail,5,KG,4,2016,94110.0000,2016.250000,0.016133
60304,237274,Iran (Islamic Republic of),Tehran,Tehran Market,Lentils,IRR,Retail,5,KG,5,2016,94760.0000,2016.333333,0.016245
60305,237275,Iran (Islamic Republic of),Tehran,Tehran Market,Lentils,IRR,Retail,5,KG,6,2016,93510.0000,2016.416667,0.016030
60306,237276,Iran (Islamic Republic of),Tehran,Tehran Market,Lentils,IRR,Retail,5,KG,7,2016,90270.0000,2016.500000,0.015475
60307,237277,Iran (Islamic Republic of),Tehran,Tehran Market,Lentils,IRR,Retail,5,KG,8,2016,93940.0000,2016.583333,0.016104
60308,237278,Iran (Islamic Republic of),Tehran,Tehran Market,Lentils,IRR,Retail,5,KG,9,2016,93980.0000,2016.666667,0.016111
60309,237279,Iran (Islamic Republic of),Tehran,Tehran Market,Lentils,IRR,Retail,5,KG,10,2016,93810.0000,2016.750000,0.016082
60310,237280,Iran (Islamic Republic of),Tehran,Tehran Market,Lentils,IRR,Retail,5,KG,11,2016,95460.0000,2016.833333,0.016365
60311,237281,Iran (Islamic Republic of),Tehran,Tehran Market,Lentils,IRR,Retail,5,KG,12,2016,96230.0000,2016.916667,0.016497
60312,237282,Iran (Islamic Republic of),Tehran,Tehran Market,Lentils,IRR,Retail,5,KG,1,2017,97630.0000,2017.000000,0.016737
60313,237283,Iran (Islamic Republic of),Tehran,Tehran Market,Lentils,IRR,Retail,5,KG,2,2017,96490.0000,2017.083333,0.016541
60314,237284,Iran (Islamic Republic of),Tehran,Tehran Market,Lentils,IRR,Retail,5,KG,3,2017,116810.0000,2017.166667,0.020025
60315,237285,Iran (Islamic Republic of),Tehran,Tehran Market,Lentils,IRR,Retail,5,KG,4,2017,96500.0000,2017.250000,0.016543
60316,237286,Iran (Islamic Republic of),Tehran,Tehran Market,Lentils,IRR,Retail,5,KG,5,2017,99800.0000,2017.333333,0.017109
60317,237287,Iran (Islamic Republic of),Tehran,Tehran Market,Lentils,IRR,Retail,5,KG,6,2017,98950.0000,2017.416667,0.016963
60318,237288,Iran (Islamic Republic of),Tehran,Tehran Market,Lentils,IRR,Retail,5,KG,7,2017,98070.0000,2017.500000,0.016812
60319,237289,Iran (Islamic Republic of),Tehran,Tehran Market,Lentils,IRR,Retail,5,KG,8,2017,97900.0000,2017.583333,0.016783
60320,237290,Iran (Islamic Republic of),Tehran,Tehran Market,Lentils,IRR,Retail,5,KG,9,2017,97900.0000,2017.666667,0.016783

# set data you want to compare

In [166]:
set_country = 'Iran  (Islamic Republic of)'
set_product = 'Eggs'
set_year1 = 1999
set_year2 = 2017

# plot data

In [167]:
# plot normalized data in Bokeh
 
x_as = normalize(select_plot(df1, set_country, set_year1, set_year2), 'Value')
y_as = normalize(select_plot_foodprices_average(df2,set_country, set_product ,set_year1,set_year2), 'average_price')    
    
output_file("Compare.html")


# create figure and it's layout
f = figure()
f = figure(plot_width=1000, plot_height=650)
f.background_fill_color="lightblue"
f.background_fill_alpha=0.1

# title
f.title.text="Refugees from Middle East to Europe"
f.title.text_font_size="25px"
f.title.align="center"

# axes labels
f.xaxis.axis_label="Amount of refugees in {}".format(set_country)
f.yaxis.axis_label="Price of {}".format(set_product)

# set range axes

# toolbar
f.toolbar_location='above'

# manual legend to get it next to the plot, not over it
    
f.circle(x_as['Normalized_data'], y_as['Normalized_data'] , color='red')
    

show(f)

ValueError: min() arg is an empty sequence