In [1]:
from sklearn import preprocessing
import numpy as np

In [3]:
def select_plot(input_data, country_of_residence, origin, year1, year2):
    input_data = input_data.loc[input_data['Country of residence'] == country_of_residence]
    input_data = input_data.loc[input_data['Origin'] == origin]
    input_data = input_data.loc[(input_data['YearMonth'] > year1) & (input_data['YearMonth'] < year2)]
    return input_data

In [20]:
import os
import pandas as pd

# normalizes data
#print(os.getcwd())

# os.chdir("../")
# os.chdir("preprocessing code/Migratiestromen/Middle East")
raw_data = pd.read_csv('refugees_middle_east_per_timestamp.csv')
df1 = pd.DataFrame(raw_data)
# print(os.getcwd())

Min = 0
Max = 0

for value in df1['Value']:
    values.append(value)

In [37]:
def normalize(input_data, column):
    values = []
    
    for value in input_data[column]:
         values.append(value)
            
    Min = min(values)
    Max = max(values)
        
    output_data = []
    for value in input_data[column]:
        output_data.append((value - Min)/(Max - Min))
    
    input_data['normalized_data'] = output_data
    
    return input_data

In [38]:
normalize(df1, 'Value')

                      Origin    Timestamp  Value  normalized_data
0       Syrian Arab Republic  1999.000000      0         0.000000
1                Afghanistan  1999.000000   1213         0.013246
2                       Iraq  1999.000000   2360         0.025771
3                    Lebanon  1999.000000    122         0.001332
4                Palestinian  1999.000000     48         0.000524
5                   Pakistan  1999.000000    491         0.005362
6     Iran (Islamic Rep. of)  1999.000000    788         0.008605
7       Syrian Arab Republic  1999.083333      0         0.000000
8                Afghanistan  1999.083333   2842         0.031035
9                       Iraq  1999.083333   4865         0.053126
10                   Lebanon  1999.083333    237         0.002588
11               Palestinian  1999.083333     92         0.001005
12                  Pakistan  1999.083333   1014         0.011073
13    Iran (Islamic Rep. of)  1999.083333   1726         0.018848
14      Syrian Arab Republic  1999.166667      0         0.000000
15               Afghanistan  1999.166667   3173         0.034649
16                      Iraq  1999.166667   5153         0.056271
17                   Lebanon  1999.166667    181         0.001977
18               Palestinian  1999.166667     79         0.000863
19                  Pakistan  1999.166667   1045         0.011411
20    Iran (Islamic Rep. of)  1999.166667   1914         0.020901
21      Syrian Arab Republic  1999.250000      0         0.000000
22               Afghanistan  1999.250000   3074         0.033568
23                      Iraq  1999.250000   5111         0.055812
24                   Lebanon  1999.250000    145         0.001583
25               Palestinian  1999.250000     68         0.000743
26                  Pakistan  1999.250000   1138         0.012427
27    Iran (Islamic Rep. of)  1999.250000   1937         0.021152
28      Syrian Arab Republic  1999.333333      0         0.000000
29               Afghanistan  1999.333333   3378         0.036888
...                      ...          ...    ...              ...
1524                Pakistan  2017.083333   4010         0.043789
1525  Iran (Islamic Rep. of)  2017.083333   3504         0.038264
1526    Syrian Arab Republic  2017.166667      0         0.000000
1527             Afghanistan  2017.166667  15853         0.173115
1528                    Iraq  2017.166667   9351         0.102113
1529                 Lebanon  2017.166667    276         0.003014
1530             Palestinian  2017.166667    408         0.004455
1531                Pakistan  2017.166667   3878         0.042348
1532  Iran (Islamic Rep. of)  2017.166667   3664         0.040011
1533    Syrian Arab Republic  2017.250000      0         0.000000
1534             Afghanistan  2017.250000  12499         0.136489
1535                    Iraq  2017.250000   8449         0.092263
1536                 Lebanon  2017.250000    258         0.002817
1537             Palestinian  2017.250000    280         0.003058
1538                Pakistan  2017.250000   2253         0.024603
1539  Iran (Islamic Rep. of)  2017.250000   3471         0.037903
1540    Syrian Arab Republic  2017.333333      0         0.000000
1541             Afghanistan  2017.333333   6956         0.075960
1542                    Iraq  2017.333333   4575         0.049959
1543                 Lebanon  2017.333333    125         0.001365
1544             Palestinian  2017.333333     97         0.001059
1545                Pakistan  2017.333333    724         0.007906
1546  Iran (Islamic Rep. of)  2017.333333   1702         0.018586
1547    Syrian Arab Republic  2017.416667      0         0.000000
1548             Afghanistan  2017.416667      0         0.000000
1549                    Iraq  2017.416667      0         0.000000
1550                 Lebanon  2017.416667      0         0.000000
1551             Palestinian  2017.416667      0         0.000000
1552                Pakistan  2017.416667      0         0.000000
1553  Iran (Islamic Rep. of)  2017.416667      0         0.000000

[1554 rows x 4 columns]