In [22]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from bokeh.plotting import figure
from bokeh.io import output_file, show, save
import pandas
from bokeh.models import DataRange1d, PanTool, ResetTool, WheelZoomTool, HoverTool, LassoSelectTool, BoxSelectTool, SaveTool, Legend
from functies_voor_selectief_plotten import normalize

ModuleNotFoundError: No module named 'functies_voor_selectief_plotten'

In [13]:
def normalize(input_data, column):
    values = []
    
    for value in input_data[column]:
         values.append(value)
            
    Min = min(values)
    Max = max(values)
        
    output_data = []
    for value in input_data[column]:
        output_data.append((value - Min)/(Max - Min))
    
    input_data['Normalized_data'] = output_data
    
    return input_data

In [15]:
# change dir to access preprocessed data

import os
print(os.getcwd())
os.chdir("../")
os.chdir("Middle-East")
print(os.getcwd())

raw_data = pd.read_csv('refugees_middle_east_per_timestamp.csv')
df1 = pd.DataFrame(raw_data)

normalize(df1, 'Value')

C:\Users\Midas\Documents\GitHub\DataProcessing1\klad\Midas\Middle-East
C:\Users\Midas\Documents\GitHub\DataProcessing1\klad\Midas\Middle-East

                      Origin    Timestamp  Value  Normalized_data
0       Syrian Arab Republic  1999.000000      0         0.000000
1                Afghanistan  1999.000000   1213         0.013246
2                       Iraq  1999.000000   2360         0.025771
3                    Lebanon  1999.000000    122         0.001332
4                Palestinian  1999.000000     48         0.000524
5                   Pakistan  1999.000000    491         0.005362
6     Iran (Islamic Rep. of)  1999.000000    788         0.008605
7       Syrian Arab Republic  1999.083333      0         0.000000
8                Afghanistan  1999.083333   2842         0.031035
9                       Iraq  1999.083333   4865         0.053126
10                   Lebanon  1999.083333    237         0.002588
11               Palestinian  1999.083333     92         0.001005
12                  Pakistan  1999.083333   1014         0.011073
13    Iran (Islamic Rep. of)  1999.083333   1726         0.018848
14      Syrian Arab Republic  1999.166667      0         0.000000
15               Afghanistan  1999.166667   3173         0.034649
16                      Iraq  1999.166667   5153         0.056271
17                   Lebanon  1999.166667    181         0.001977
18               Palestinian  1999.166667     79         0.000863
19                  Pakistan  1999.166667   1045         0.011411
20    Iran (Islamic Rep. of)  1999.166667   1914         0.020901
21      Syrian Arab Republic  1999.250000      0         0.000000
22               Afghanistan  1999.250000   3074         0.033568
23                      Iraq  1999.250000   5111         0.055812
24                   Lebanon  1999.250000    145         0.001583
25               Palestinian  1999.250000     68         0.000743
26                  Pakistan  1999.250000   1138         0.012427
27    Iran (Islamic Rep. of)  1999.250000   1937         0.021152
28      Syrian Arab Republic  1999.333333      0         0.000000
29               Afghanistan  1999.333333   3378         0.036888
...                      ...          ...    ...              ...
1524                Pakistan  2017.083333   4010         0.043789
1525  Iran (Islamic Rep. of)  2017.083333   3504         0.038264
1526    Syrian Arab Republic  2017.166667      0         0.000000
1527             Afghanistan  2017.166667  15853         0.173115
1528                    Iraq  2017.166667   9351         0.102113
1529                 Lebanon  2017.166667    276         0.003014
1530             Palestinian  2017.166667    408         0.004455
1531                Pakistan  2017.166667   3878         0.042348
1532  Iran (Islamic Rep. of)  2017.166667   3664         0.040011
1533    Syrian Arab Republic  2017.250000      0         0.000000
1534             Afghanistan  2017.250000  12499         0.136489
1535                    Iraq  2017.250000   8449         0.092263
1536                 Lebanon  2017.250000    258         0.002817
1537             Palestinian  2017.250000    280         0.003058
1538                Pakistan  2017.250000   2253         0.024603
1539  Iran (Islamic Rep. of)  2017.250000   3471         0.037903
1540    Syrian Arab Republic  2017.333333      0         0.000000
1541             Afghanistan  2017.333333   6956         0.075960
1542                    Iraq  2017.333333   4575         0.049959
1543                 Lebanon  2017.333333    125         0.001365
1544             Palestinian  2017.333333     97         0.001059
1545                Pakistan  2017.333333    724         0.007906
1546  Iran (Islamic Rep. of)  2017.333333   1702         0.018586
1547    Syrian Arab Republic  2017.416667      0         0.000000
1548             Afghanistan  2017.416667      0         0.000000
1549                    Iraq  2017.416667      0         0.000000
1550                 Lebanon  2017.416667      0         0.000000
1551             Palestinian  2017.416667      0         0.000000
1552                Pakistan  2017.416667      0         0.000000
1553  Iran (Islamic Rep. of)  2017.416667      0         0.000000

[1554 rows x 4 columns]

In [16]:
import os
print(os.getcwd())
os.chdir("../")
os.chdir("Africa")
print(os.getcwd())

raw_data = pd.read_csv('refugees_africa_per_timestamp.csv')
df2 = pd.DataFrame(raw_data)

normalize(df2, 'Value')

C:\Users\Midas\Documents\GitHub\DataProcessing1\klad\Midas\Middle-East
C:\Users\Midas\Documents\GitHub\DataProcessing1\klad\Midas\Africa

                    Origin    Timestamp  Value  Normalized_data
0               Cabo Verde  1999.000000      0         0.000000
1     Central African Rep.  1999.000000      9         0.000796
2                  Burundi  1999.000000     50         0.004420
3                    Congo  1999.000000    146         0.012908
4                 Djibouti  1999.000000      8         0.000707
5                 Ehtiopia  1999.000000      0         0.000000
6                   Gambia  1999.000000      9         0.000796
7                   Guinea  1999.000000     95         0.008399
8                    Kenya  1999.000000     56         0.004951
9                  Lesotho  1999.000000      0         0.000000
10                 Liberia  1999.000000     45         0.003978
11              Madagascar  1999.000000      0         0.000000
12                  Malawi  1999.000000      0         0.000000
13                    Mali  1999.000000    117         0.010344
14              Mauritania  1999.000000     86         0.007603
15              Mozambique  1999.000000      0         0.000000
16                   Niger  1999.000000     14         0.001238
17                 Nigeria  1999.000000    263         0.023252
18                  Rwanda  1999.000000    189         0.016709
19                 Senegal  1999.000000     26         0.002299
20                 Somalia  1999.000000   1109         0.098046
21             South Sudan  1999.000000      0         0.000000
22                   Sudan  1999.000000    231         0.020423
23                  Uganda  1999.000000     26         0.002299
24                Tanzania  1999.000000      0         0.000000
25                  Zambia  1999.000000      0         0.000000
26                Zimbabwe  1999.000000     16         0.001415
27              Cabo Verde  1999.083333      0         0.000000
28    Central African Rep.  1999.083333     21         0.001857
29                 Burundi  1999.083333     92         0.008134
...                    ...          ...    ...              ...
5937              Tanzania  2017.250000      0         0.000000
5938                Zambia  2017.250000      0         0.000000
5939              Zimbabwe  2017.250000     27         0.002387
5940            Cabo Verde  2017.333333      0         0.000000
5941  Central African Rep.  2017.333333     26         0.002299
5942               Burundi  2017.333333     40         0.003536
5943                 Congo  2017.333333     98         0.008664
5944              Djibouti  2017.333333    116         0.010256
5945              Ehtiopia  2017.333333      0         0.000000
5946                Gambia  2017.333333    260         0.022986
5947                Guinea  2017.333333    839         0.074176
5948                 Kenya  2017.333333     29         0.002564
5949               Lesotho  2017.333333      0         0.000000
5950               Liberia  2017.333333     16         0.001415
5951            Madagascar  2017.333333     11         0.000973
5952                Malawi  2017.333333      0         0.000000
5953                  Mali  2017.333333    213         0.018831
5954            Mauritania  2017.333333     76         0.006719
5955            Mozambique  2017.333333      0         0.000000
5956                 Niger  2017.333333     26         0.002299
5957               Nigeria  2017.333333    793         0.070109
5958                Rwanda  2017.333333     31         0.002741
5959               Senegal  2017.333333    153         0.013527
5960               Somalia  2017.333333   1004         0.088763
5961           South Sudan  2017.333333      5         0.000442
5962                 Sudan  2017.333333    565         0.049951
5963                Uganda  2017.333333     23         0.002033
5964              Tanzania  2017.333333      0         0.000000
5965                Zambia  2017.333333      0         0.000000
5966              Zimbabwe  2017.333333     13         0.001149

[5967 rows x 4 columns]

In [ ]:
# plot data of new csv in Bokeh
 
output_file("Compare.html")

colormap = ['red', 'green','blue', 'brown', 'black', 'yellow','violet']

count = 0

# create figure and it's layout
f = figure()
f = figure(plot_width=1000, plot_height=650)
f.background_fill_color="lightblue"
f.background_fill_alpha=0.1

# title
f.title.text="Refugees from Middle East to Europe"
f.title.text_font_size="25px"
f.title.align="center"

# axes labels
f.xaxis.axis_label="Years"
f.yaxis.axis_label="Amount of refugees"

# set range axes
f.x_range=DataRange1d(start=1999, end=2017.34)
f.y_range=DataRange1d(start=0, end=18000)

# toolbar
f.toolbar_location='above'

# manual legend to get it next to the plot, not over it
legend_it = []

for origin in middle_eastern_countries:    
    
    f.circle(select_plot1(df1, origin,1999,2017.34)["Timestamp"], 
             select_plot1(df1,origin,1999,2017.34)["Value"] , 
             color=colormap[count])
    
    legend_it.append((origin, [f.circle(select_plot1(df1, origin,1999,2017.34)["Timestamp"], 
             select_plot1(df1,origin,1999,2017.34)["Value"] , 
             color=colormap[count])]))
    
    count += 1
    
    


legend = Legend(items=legend_it, location=(0, 381))
legend.click_policy="mute"

f.add_layout(legend, 'right')

show(f)